// Generated by ../generate-mercenary-build-skills.mjs. Do not edit manually.
// Relationships: https://poedb.tw/us/Mercenaries
// Build and skill IDs: official Path of Exile trade metadata.

export interface MercenaryBuildSkillIds {
  primary: string[]
  secondary: string[]
  utility: string[]
}

export const MERCENARY_BUILD_SKILL_IDS: Readonly<Record<string, MercenaryBuildSkillIds>> = {
  AurasMinionsTemplarSmite: {
    primary: ['mercenary.skill_40812', 'mercenary.skill_55917'],
    secondary: ['mercenary.skill_50866', 'mercenary.skill_43742', 'mercenary.skill_47078', 'mercenary.skill_39732'],
    utility: ['mercenary.skill_63233', 'mercenary.skill_56180', 'mercenary.skill_34212']
  },
  AurasMinionsTemplarSmiteNoble: {
    primary: ['mercenary.skill_40812', 'mercenary.skill_55917'],
    secondary: ['mercenary.skill_50866', 'mercenary.skill_43742', 'mercenary.skill_47078', 'mercenary.skill_39732'],
    utility: ['mercenary.skill_63233', 'mercenary.skill_56180', 'mercenary.skill_34212']
  },
  AurasMinionsTemplarSpectres: {
    primary: ['mercenary.skill_15611', 'mercenary.skill_50349', 'mercenary.skill_21523'],
    secondary: ['mercenary.skill_4383', 'mercenary.skill_61523', 'mercenary.skill_53527'],
    utility: ['mercenary.skill_38326', 'mercenary.skill_14498', 'mercenary.skill_37344', 'mercenary.skill_56180', 'mercenary.skill_40470']
  },
  AurasMinionsTemplarSpectresNoble: {
    primary: ['mercenary.skill_15611', 'mercenary.skill_50349', 'mercenary.skill_21523'],
    secondary: ['mercenary.skill_4383', 'mercenary.skill_61523', 'mercenary.skill_53527'],
    utility: ['mercenary.skill_38326', 'mercenary.skill_14498', 'mercenary.skill_37344', 'mercenary.skill_56180', 'mercenary.skill_40470']
  },
  AurasMinionsTemplarStaff: {
    primary: ['mercenary.skill_28506', 'mercenary.skill_38655'],
    secondary: ['mercenary.skill_7395', 'mercenary.skill_53518', 'mercenary.skill_3093'],
    utility: ['mercenary.skill_63233', 'mercenary.skill_56180', 'mercenary.skill_34212', 'mercenary.skill_38326']
  },
  AurasMinionsTemplarStaffNoble: {
    primary: ['mercenary.skill_28506', 'mercenary.skill_38655'],
    secondary: ['mercenary.skill_7395', 'mercenary.skill_53518', 'mercenary.skill_3093'],
    utility: ['mercenary.skill_63233', 'mercenary.skill_56180', 'mercenary.skill_34212', 'mercenary.skill_38326']
  },
  ChaosMinionWitchChaosHit: {
    primary: ['mercenary.skill_56742', 'mercenary.skill_52783'],
    secondary: ['mercenary.skill_35371', 'mercenary.skill_52144', 'mercenary.skill_10742', 'mercenary.skill_29071', 'mercenary.skill_54144', 'mercenary.skill_51539'],
    utility: ['mercenary.skill_14498', 'mercenary.skill_28757', 'mercenary.skill_40470', 'mercenary.skill_56180', 'mercenary.skill_17515']
  },
  ChaosMinionWitchChaosHitNoble: {
    primary: ['mercenary.skill_56742', 'mercenary.skill_52783'],
    secondary: ['mercenary.skill_35371', 'mercenary.skill_52144', 'mercenary.skill_10742', 'mercenary.skill_29071', 'mercenary.skill_54144', 'mercenary.skill_51539'],
    utility: ['mercenary.skill_14498', 'mercenary.skill_28757', 'mercenary.skill_40470', 'mercenary.skill_56180', 'mercenary.skill_17515']
  },
  ChaosMinionWitchDot: {
    primary: ['mercenary.skill_63468', 'mercenary.skill_7383'],
    secondary: ['mercenary.skill_11671', 'mercenary.skill_13441', 'mercenary.skill_8450', 'mercenary.skill_39669', 'mercenary.skill_50670'],
    utility: ['mercenary.skill_1516', 'mercenary.skill_28757', 'mercenary.skill_40470', 'mercenary.skill_56180', 'mercenary.skill_28785', 'mercenary.skill_10320', 'mercenary.skill_1911']
  },
  ChaosMinionWitchDotNoble: {
    primary: ['mercenary.skill_63468', 'mercenary.skill_7383'],
    secondary: ['mercenary.skill_11671', 'mercenary.skill_13441', 'mercenary.skill_8450', 'mercenary.skill_39669', 'mercenary.skill_50670'],
    utility: ['mercenary.skill_1516', 'mercenary.skill_28757', 'mercenary.skill_40470', 'mercenary.skill_56180', 'mercenary.skill_28785', 'mercenary.skill_10320', 'mercenary.skill_1911']
  },
  ChaosMinionWitchInstability: {
    primary: ['mercenary.skill_52491', 'mercenary.skill_21523'],
    secondary: ['mercenary.skill_57377', 'mercenary.skill_17409', 'mercenary.skill_61730', 'mercenary.skill_44467', 'mercenary.skill_19108'],
    utility: ['mercenary.skill_28757', 'mercenary.skill_40470', 'mercenary.skill_56180', 'mercenary.skill_26391', 'mercenary.skill_62758']
  },
  ChaosMinionWitchInstabilityNoble: {
    primary: ['mercenary.skill_52491', 'mercenary.skill_21523'],
    secondary: ['mercenary.skill_57377', 'mercenary.skill_17409', 'mercenary.skill_61730', 'mercenary.skill_44467', 'mercenary.skill_19108'],
    utility: ['mercenary.skill_28757', 'mercenary.skill_40470', 'mercenary.skill_56180', 'mercenary.skill_26391', 'mercenary.skill_62758']
  },
  Crit1HShadowPhysSpell: {
    primary: ['mercenary.skill_26057', 'mercenary.skill_22724'],
    secondary: ['mercenary.skill_17198', 'mercenary.skill_37202', 'mercenary.skill_25718', 'mercenary.skill_50999', 'mercenary.skill_59477'],
    utility: ['mercenary.skill_60723', 'mercenary.skill_2792', 'mercenary.skill_56180', 'mercenary.skill_19417', 'mercenary.skill_57491']
  },
  Crit1HShadowPhysSpellNoble: {
    primary: ['mercenary.skill_26057', 'mercenary.skill_22724'],
    secondary: ['mercenary.skill_17198', 'mercenary.skill_37202', 'mercenary.skill_25718', 'mercenary.skill_50999', 'mercenary.skill_59477'],
    utility: ['mercenary.skill_60723', 'mercenary.skill_2792', 'mercenary.skill_56180', 'mercenary.skill_19417', 'mercenary.skill_57491']
  },
  Crit1HShadowPoison: {
    primary: ['mercenary.skill_22227', 'mercenary.skill_14992'],
    secondary: ['mercenary.skill_59831', 'mercenary.skill_36446', 'mercenary.skill_16896', 'mercenary.skill_12262'],
    utility: ['mercenary.skill_10823', 'mercenary.skill_60723', 'mercenary.skill_1516', 'mercenary.skill_10320', 'mercenary.skill_2792']
  },
  Crit1HShadowPoisonNoble: {
    primary: ['mercenary.skill_22227', 'mercenary.skill_14992'],
    secondary: ['mercenary.skill_59831', 'mercenary.skill_36446', 'mercenary.skill_16896', 'mercenary.skill_12262'],
    utility: ['mercenary.skill_10823', 'mercenary.skill_60723', 'mercenary.skill_1516', 'mercenary.skill_10320', 'mercenary.skill_2792']
  },
  DivingDuelist: {
    primary: ['mercenary.skill_8708', 'mercenary.skill_10557'],
    secondary: ['mercenary.skill_22105', 'mercenary.skill_40957', 'mercenary.skill_32807'],
    utility: ['mercenary.skill_24482', 'mercenary.skill_13693', 'mercenary.skill_40470', 'mercenary.skill_60723']
  },
  DivingDuelistNoble: {
    primary: ['mercenary.skill_8708', 'mercenary.skill_10557'],
    secondary: ['mercenary.skill_22105', 'mercenary.skill_40957', 'mercenary.skill_32807'],
    utility: ['mercenary.skill_24482', 'mercenary.skill_13693', 'mercenary.skill_40470', 'mercenary.skill_60723']
  },
  EleBowRangerClones: {
    primary: ['mercenary.skill_11495', 'mercenary.skill_58425'],
    secondary: ['mercenary.skill_16381', 'mercenary.skill_18232', 'mercenary.skill_24409', 'mercenary.skill_65447'],
    utility: ['mercenary.skill_24482', 'mercenary.skill_10557', 'mercenary.skill_2792', 'mercenary.skill_60723', 'mercenary.skill_10722']
  },
  EleBowRangerClonesNoble: {
    primary: ['mercenary.skill_11495', 'mercenary.skill_58425'],
    secondary: ['mercenary.skill_16381', 'mercenary.skill_18232', 'mercenary.skill_24409', 'mercenary.skill_65447'],
    utility: ['mercenary.skill_24482', 'mercenary.skill_10557', 'mercenary.skill_2792', 'mercenary.skill_60723', 'mercenary.skill_10722']
  },
  EleBowRangerFire: {
    primary: ['mercenary.skill_34665', 'mercenary.skill_24179'],
    secondary: ['mercenary.skill_23512', 'mercenary.skill_59200', 'mercenary.skill_35610', 'mercenary.skill_36298', 'mercenary.skill_18004', 'mercenary.skill_21962'],
    utility: ['mercenary.skill_2792', 'mercenary.skill_10722', 'mercenary.skill_60723', 'mercenary.skill_39298']
  },
  EleBowRangerFireNoble: {
    primary: ['mercenary.skill_34665', 'mercenary.skill_24179'],
    secondary: ['mercenary.skill_23512', 'mercenary.skill_59200', 'mercenary.skill_35610', 'mercenary.skill_36298', 'mercenary.skill_18004', 'mercenary.skill_21962'],
    utility: ['mercenary.skill_2792', 'mercenary.skill_10722', 'mercenary.skill_60723', 'mercenary.skill_39298']
  },
  EleBowRangerLightning: {
    primary: ['mercenary.skill_41051', 'mercenary.skill_47406'],
    secondary: ['mercenary.skill_27165', 'mercenary.skill_38993', 'mercenary.skill_22000', 'mercenary.skill_17216'],
    utility: ['mercenary.skill_38326', 'mercenary.skill_10722', 'mercenary.skill_38072', 'mercenary.skill_36279', 'mercenary.skill_60723']
  },
  ElementalWitchCold: {
    primary: ['mercenary.skill_10557', 'mercenary.skill_6479'],
    secondary: ['mercenary.skill_50009', 'mercenary.skill_57063', 'mercenary.skill_31928', 'mercenary.skill_33663', 'mercenary.skill_61497', 'mercenary.skill_61471', 'mercenary.skill_28637'],
    utility: ['mercenary.skill_28757', 'mercenary.skill_40470', 'mercenary.skill_56180', 'mercenary.skill_13693', 'mercenary.skill_21708']
  },
  ElementalWitchColdNoble: {
    primary: ['mercenary.skill_10557', 'mercenary.skill_6479'],
    secondary: ['mercenary.skill_50009', 'mercenary.skill_57063', 'mercenary.skill_31928', 'mercenary.skill_33663', 'mercenary.skill_61497', 'mercenary.skill_61471', 'mercenary.skill_28637'],
    utility: ['mercenary.skill_28757', 'mercenary.skill_40470', 'mercenary.skill_56180', 'mercenary.skill_13693', 'mercenary.skill_21708']
  },
  ElementalWitchFire: {
    primary: ['mercenary.skill_57450', 'mercenary.skill_40521'],
    secondary: ['mercenary.skill_24099', 'mercenary.skill_6446', 'mercenary.skill_29426', 'mercenary.skill_324', 'mercenary.skill_37821', 'mercenary.skill_30130', 'mercenary.skill_8801'],
    utility: ['mercenary.skill_28757', 'mercenary.skill_40470', 'mercenary.skill_33728', 'mercenary.skill_13235', 'mercenary.skill_50414']
  },
  ElementalWitchLightning: {
    primary: ['mercenary.skill_41484', 'mercenary.skill_33661'],
    secondary: ['mercenary.skill_5893', 'mercenary.skill_59005', 'mercenary.skill_30663', 'mercenary.skill_3148', 'mercenary.skill_50290', 'mercenary.skill_11879', 'mercenary.skill_7549'],
    utility: ['mercenary.skill_28757', 'mercenary.skill_40470', 'mercenary.skill_56180', 'mercenary.skill_38326', 'mercenary.skill_63233', 'mercenary.skill_16018']
  },
  ElementalWitchLightningNoble: {
    primary: ['mercenary.skill_41484', 'mercenary.skill_33661'],
    secondary: ['mercenary.skill_5893', 'mercenary.skill_59005', 'mercenary.skill_30663', 'mercenary.skill_3148', 'mercenary.skill_50290', 'mercenary.skill_11879', 'mercenary.skill_7549'],
    utility: ['mercenary.skill_28757', 'mercenary.skill_40470', 'mercenary.skill_56180', 'mercenary.skill_38326', 'mercenary.skill_63233', 'mercenary.skill_16018']
  },
  MeleeAOEMarauderFireSlam: {
    primary: ['mercenary.skill_59259', 'mercenary.skill_2135', 'mercenary.skill_18149'],
    secondary: ['mercenary.skill_53235', 'mercenary.skill_3093', 'mercenary.skill_6228', 'mercenary.skill_42361'],
    utility: ['mercenary.skill_21036', 'mercenary.skill_52845', 'mercenary.skill_33728', 'mercenary.skill_44334', 'mercenary.skill_47364']
  },
  MeleeAOEMarauderFireSlamNoble: {
    primary: ['mercenary.skill_59259', 'mercenary.skill_2135', 'mercenary.skill_18149'],
    secondary: ['mercenary.skill_53235', 'mercenary.skill_3093', 'mercenary.skill_6228', 'mercenary.skill_42361'],
    utility: ['mercenary.skill_21036', 'mercenary.skill_52845', 'mercenary.skill_33728', 'mercenary.skill_44334', 'mercenary.skill_47364']
  },
  MeleeAOEMarauderNonSlam: {
    primary: ['mercenary.skill_52105', 'mercenary.skill_62530'],
    secondary: ['mercenary.skill_8445', 'mercenary.skill_12723', 'mercenary.skill_19808', 'mercenary.skill_7182', 'mercenary.skill_41915'],
    utility: ['mercenary.skill_21036', 'mercenary.skill_52845', 'mercenary.skill_2135', 'mercenary.skill_40419']
  },
  MeleeAOEMarauderNonSlamNoble: {
    primary: ['mercenary.skill_52105', 'mercenary.skill_62530'],
    secondary: ['mercenary.skill_8445', 'mercenary.skill_12723', 'mercenary.skill_19808', 'mercenary.skill_7182', 'mercenary.skill_41915'],
    utility: ['mercenary.skill_21036', 'mercenary.skill_52845', 'mercenary.skill_2135', 'mercenary.skill_40419']
  },
  MeleeAOEMarauderPhysSlam: {
    primary: ['mercenary.skill_38311', 'mercenary.skill_2135'],
    secondary: ['mercenary.skill_10712', 'mercenary.skill_53728', 'mercenary.skill_41346', 'mercenary.skill_40527', 'mercenary.skill_17654'],
    utility: ['mercenary.skill_52845', 'mercenary.skill_21036', 'mercenary.skill_31440', 'mercenary.skill_57171', 'mercenary.skill_14889']
  },
  MeleeAOEMarauderPhysSlamNoble: {
    primary: ['mercenary.skill_38311', 'mercenary.skill_2135'],
    secondary: ['mercenary.skill_10712', 'mercenary.skill_53728', 'mercenary.skill_41346', 'mercenary.skill_40527', 'mercenary.skill_17654'],
    utility: ['mercenary.skill_52845', 'mercenary.skill_21036', 'mercenary.skill_31440', 'mercenary.skill_57171', 'mercenary.skill_14889']
  },
  MeleeAOEStrikeDuelistCyclone: {
    primary: ['mercenary.skill_46739', 'mercenary.skill_39265', 'mercenary.skill_28026'],
    secondary: ['mercenary.skill_61669', 'mercenary.skill_37132'],
    utility: ['mercenary.skill_18793', 'mercenary.skill_2135', 'mercenary.skill_59409', 'mercenary.skill_60723', 'mercenary.skill_17105']
  },
  MeleeAOEStrikeDuelistCycloneNoble: {
    primary: ['mercenary.skill_46739', 'mercenary.skill_39265', 'mercenary.skill_28026'],
    secondary: ['mercenary.skill_61669', 'mercenary.skill_37132'],
    utility: ['mercenary.skill_18793', 'mercenary.skill_2135', 'mercenary.skill_59409', 'mercenary.skill_60723', 'mercenary.skill_17105']
  },
  MeleeAOEStrikeDuelistRangeStrikes: {
    primary: ['mercenary.skill_65473', 'mercenary.skill_32807'],
    secondary: ['mercenary.skill_22105', 'mercenary.skill_40957', 'mercenary.skill_37916', 'mercenary.skill_24931'],
    utility: ['mercenary.skill_38326', 'mercenary.skill_60723', 'mercenary.skill_40470', 'mercenary.skill_13693']
  },
  MeleeAOEStrikeDuelistRangeStrikesNoble: {
    primary: ['mercenary.skill_65473', 'mercenary.skill_32807'],
    secondary: ['mercenary.skill_22105', 'mercenary.skill_40957', 'mercenary.skill_37916', 'mercenary.skill_24931'],
    utility: ['mercenary.skill_38326', 'mercenary.skill_60723', 'mercenary.skill_40470', 'mercenary.skill_13693']
  },
  MeleeStrikesMaraduerPhys: {
    primary: ['mercenary.skill_4988', 'mercenary.skill_20973', 'mercenary.skill_17015'],
    secondary: ['mercenary.skill_64565', 'mercenary.skill_22696', 'mercenary.skill_10235'],
    utility: ['mercenary.skill_52845', 'mercenary.skill_2135', 'mercenary.skill_21036', 'mercenary.skill_40419', 'mercenary.skill_38521', 'mercenary.skill_38104']
  },
  MeleeStrikesMaraduerPhysNoble: {
    primary: ['mercenary.skill_4988', 'mercenary.skill_20973', 'mercenary.skill_17015'],
    secondary: ['mercenary.skill_64565', 'mercenary.skill_22696', 'mercenary.skill_10235'],
    utility: ['mercenary.skill_52845', 'mercenary.skill_2135', 'mercenary.skill_21036', 'mercenary.skill_40419', 'mercenary.skill_38521', 'mercenary.skill_38104']
  },
  MeleeStrikesMarauderFire: {
    primary: ['mercenary.skill_32391', 'mercenary.skill_8295'],
    secondary: ['mercenary.skill_42219', 'mercenary.skill_17147', 'mercenary.skill_899', 'mercenary.skill_19178'],
    utility: ['mercenary.skill_13235', 'mercenary.skill_2135', 'mercenary.skill_21036', 'mercenary.skill_50414', 'mercenary.skill_59259']
  },
  MiscScionPhysDot: {
    primary: ['mercenary.skill_44422', 'mercenary.skill_2187', 'mercenary.skill_4927'],
    secondary: ['mercenary.skill_40439', 'mercenary.skill_1185', 'mercenary.skill_14064', 'mercenary.skill_8958'],
    utility: ['mercenary.skill_56180', 'mercenary.skill_28757', 'mercenary.skill_18793', 'mercenary.skill_16018', 'mercenary.skill_14889']
  },
  MiscScionPhysDotNoble: {
    primary: ['mercenary.skill_44422', 'mercenary.skill_2187', 'mercenary.skill_4927'],
    secondary: ['mercenary.skill_40439', 'mercenary.skill_1185', 'mercenary.skill_14064', 'mercenary.skill_8958'],
    utility: ['mercenary.skill_56180', 'mercenary.skill_28757', 'mercenary.skill_18793', 'mercenary.skill_16018', 'mercenary.skill_14889']
  },
  MiscScionWandAttacks: {
    primary: ['mercenary.skill_5689', 'mercenary.skill_57450'],
    secondary: ['mercenary.skill_12583', 'mercenary.skill_26705', 'mercenary.skill_1356', 'mercenary.skill_44258', 'mercenary.skill_16356', 'mercenary.skill_32089'],
    utility: ['mercenary.skill_56180', 'mercenary.skill_40470', 'mercenary.skill_52155', 'mercenary.skill_65473']
  },
  MiscScionWandAttacksNoble: {
    primary: ['mercenary.skill_5689', 'mercenary.skill_57450'],
    secondary: ['mercenary.skill_12583', 'mercenary.skill_26705', 'mercenary.skill_1356', 'mercenary.skill_44258', 'mercenary.skill_16356', 'mercenary.skill_32089'],
    utility: ['mercenary.skill_56180', 'mercenary.skill_40470', 'mercenary.skill_52155', 'mercenary.skill_65473']
  },
  NonEleBowRangerChaos: {
    primary: ['mercenary.skill_10320', 'mercenary.skill_26913', 'mercenary.skill_18986'],
    secondary: ['mercenary.skill_36274', 'mercenary.skill_38628', 'mercenary.skill_28502', 'mercenary.skill_58174'],
    utility: ['mercenary.skill_2792', 'mercenary.skill_10722', 'mercenary.skill_60723', 'mercenary.skill_1516', 'mercenary.skill_38072']
  },
  NonEleBowRangerChaosNoble: {
    primary: ['mercenary.skill_10320', 'mercenary.skill_26913', 'mercenary.skill_18986'],
    secondary: ['mercenary.skill_36274', 'mercenary.skill_38628', 'mercenary.skill_28502', 'mercenary.skill_58174'],
    utility: ['mercenary.skill_2792', 'mercenary.skill_10722', 'mercenary.skill_60723', 'mercenary.skill_1516', 'mercenary.skill_38072']
  },
  NonEleBowRangerPhys: {
    primary: ['mercenary.skill_12667', 'mercenary.skill_27805'],
    secondary: ['mercenary.skill_8546', 'mercenary.skill_40759', 'mercenary.skill_8030', 'mercenary.skill_61903', 'mercenary.skill_12260', 'mercenary.skill_44144', 'mercenary.skill_43202', 'mercenary.skill_30431'],
    utility: ['mercenary.skill_2792', 'mercenary.skill_10722', 'mercenary.skill_60723', 'mercenary.skill_58592', 'mercenary.skill_52155']
  },
  NonEleBowRangerPhysNoble: {
    primary: ['mercenary.skill_12667', 'mercenary.skill_27805'],
    secondary: ['mercenary.skill_8546', 'mercenary.skill_40759', 'mercenary.skill_8030', 'mercenary.skill_61903', 'mercenary.skill_12260', 'mercenary.skill_44144', 'mercenary.skill_43202', 'mercenary.skill_30431'],
    utility: ['mercenary.skill_2792', 'mercenary.skill_10722', 'mercenary.skill_60723', 'mercenary.skill_58592', 'mercenary.skill_52155']
  },
  PhysConvertTemplarCold: {
    primary: ['mercenary.skill_57491', 'mercenary.skill_47031'],
    secondary: ['mercenary.skill_11018', 'mercenary.skill_53217', 'mercenary.skill_14816', 'mercenary.skill_38103'],
    utility: ['mercenary.skill_24482', 'mercenary.skill_40470', 'mercenary.skill_10557', 'mercenary.skill_55367', 'mercenary.skill_13693']
  },
  PhysConvertTemplarFire: {
    primary: ['mercenary.skill_47949', 'mercenary.skill_17763'],
    secondary: ['mercenary.skill_1577', 'mercenary.skill_4286', 'mercenary.skill_47293', 'mercenary.skill_40723'],
    utility: ['mercenary.skill_28757', 'mercenary.skill_56180', 'mercenary.skill_44334', 'mercenary.skill_13235']
  },
  PhysConvertTemplarLightning: {
    primary: ['mercenary.skill_19034', 'mercenary.skill_14732'],
    secondary: ['mercenary.skill_45226', 'mercenary.skill_23225', 'mercenary.skill_24685', 'mercenary.skill_6651'],
    utility: ['mercenary.skill_5673', 'mercenary.skill_38326', 'mercenary.skill_28757', 'mercenary.skill_56180']
  },
  PhysConvertTemplarLightningNoble: {
    primary: ['mercenary.skill_19034', 'mercenary.skill_14732'],
    secondary: ['mercenary.skill_45226', 'mercenary.skill_23225', 'mercenary.skill_24685', 'mercenary.skill_6651'],
    utility: ['mercenary.skill_5673', 'mercenary.skill_38326', 'mercenary.skill_28757', 'mercenary.skill_56180']
  },
  PhysicalDuelistBleed: {
    primary: ['mercenary.skill_60880', 'mercenary.skill_26931', 'mercenary.skill_8136'],
    secondary: ['mercenary.skill_12357', 'mercenary.skill_54006'],
    utility: ['mercenary.skill_2135', 'mercenary.skill_60723', 'mercenary.skill_52845', 'mercenary.skill_19268']
  },
  PhysicalDuelistBleedNoble: {
    primary: ['mercenary.skill_60880', 'mercenary.skill_26931', 'mercenary.skill_8136'],
    secondary: ['mercenary.skill_12357', 'mercenary.skill_54006'],
    utility: ['mercenary.skill_2135', 'mercenary.skill_60723', 'mercenary.skill_52845', 'mercenary.skill_19268']
  },
  PhysicalDuelistShields: {
    primary: ['mercenary.skill_21201', 'mercenary.skill_22850'],
    secondary: ['mercenary.skill_41834', 'mercenary.skill_58855', 'mercenary.skill_52494'],
    utility: ['mercenary.skill_52845', 'mercenary.skill_60723', 'mercenary.skill_38311', 'mercenary.skill_17015', 'mercenary.skill_45615']
  },
  PhysicalDuelistShieldsNoble: {
    primary: ['mercenary.skill_21201', 'mercenary.skill_22850'],
    secondary: ['mercenary.skill_41834', 'mercenary.skill_58855', 'mercenary.skill_52494'],
    utility: ['mercenary.skill_52845', 'mercenary.skill_60723', 'mercenary.skill_38311', 'mercenary.skill_17015', 'mercenary.skill_45615']
  },
  PhysicalDuelistSteel: {
    primary: ['mercenary.skill_46131', 'mercenary.skill_39265', 'mercenary.skill_28026'],
    secondary: ['mercenary.skill_12729', 'mercenary.skill_28511', 'mercenary.skill_43812'],
    utility: ['mercenary.skill_60723', 'mercenary.skill_10823', 'mercenary.skill_2792', 'mercenary.skill_27763']
  },
  TrapsMinesShadowAttack: {
    primary: ['mercenary.skill_11054', 'mercenary.skill_38072'],
    secondary: ['mercenary.skill_62393', 'mercenary.skill_28988'],
    utility: ['mercenary.skill_64528', 'mercenary.skill_56180', 'mercenary.skill_2792', 'mercenary.skill_44296', 'mercenary.skill_13711']
  },
  TrapsMinesShadowAttackNoble: {
    primary: ['mercenary.skill_11054', 'mercenary.skill_38072'],
    secondary: ['mercenary.skill_62393', 'mercenary.skill_28988'],
    utility: ['mercenary.skill_64528', 'mercenary.skill_56180', 'mercenary.skill_2792', 'mercenary.skill_44296', 'mercenary.skill_13711']
  },
  TrapsMinesShadowCold: {
    primary: ['mercenary.skill_57491', 'mercenary.skill_3493'],
    secondary: ['mercenary.skill_62997', 'mercenary.skill_9321'],
    utility: ['mercenary.skill_44296', 'mercenary.skill_56180', 'mercenary.skill_40470', 'mercenary.skill_2792', 'mercenary.skill_55367', 'mercenary.skill_44455']
  },
  TrapsMinesShadowLightning: {
    primary: ['mercenary.skill_41484', 'mercenary.skill_25149'],
    secondary: ['mercenary.skill_17037', 'mercenary.skill_8075', 'mercenary.skill_37561', 'mercenary.skill_5247'],
    utility: ['mercenary.skill_56180', 'mercenary.skill_40470', 'mercenary.skill_64528', 'mercenary.skill_44296', 'mercenary.skill_14498']
  },
  TrapsMinesShadowLightningNoble: {
    primary: ['mercenary.skill_41484', 'mercenary.skill_25149'],
    secondary: ['mercenary.skill_17037', 'mercenary.skill_8075', 'mercenary.skill_37561', 'mercenary.skill_5247'],
    utility: ['mercenary.skill_56180', 'mercenary.skill_40470', 'mercenary.skill_64528', 'mercenary.skill_44296', 'mercenary.skill_14498']
  }
}
